#!/usr/bin/env python3
"""
Build script: merge all TCL files into a single orcad_checker_all.tcl
Usage: python build_bundle.py
Output: dist/orcad_checker_all.tcl
"""

import os
import re
import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DIST_DIR = os.path.join(SCRIPT_DIR, "dist")

# Files in dependency order
BUNDLE_ORDER = [
    # 1. DBO API adapter (must be first)
    "lib/orcad_api.tcl",
    # 2. Check engine
    "engine/check_engine.tcl",
    # 3. All checkers
    "checkers/duplicate_refdes.tcl",
    "checkers/missing_attributes.tcl",
    "checkers/unconnected_pins.tcl",
    "checkers/footprint_validation.tcl",
    "checkers/power_net_naming.tcl",
    "checkers/net_naming.tcl",
    "checkers/single_pin_nets.tcl",
    # 4. JSON export utilities
    "export_json.tcl",
    # 5. Data extraction helpers
    "lib/components.tcl",
    "lib/nets.tcl",
    "lib/power.tcl",
    # 6. HTTP client
    "engine/http_client.tcl",
    # 7. Design extraction entry
    # (extract_design.tcl - inlined below, minus source lines)
    # 8. GUI
    "gui/main_window.tcl",
]

# Lines to strip from individual files (source/path setup that only
# makes sense in multi-file mode)
STRIP_PATTERNS = [
    re.compile(r'^\s*set\s+_\w+\s+\[file\s+dirname\s+\[info\s+script\]\]'),
    re.compile(r'^\s*set\s+script_dir\s+\[file\s+dirname'),
    re.compile(r'^\s*source\s+\[file\s+join\s'),
    re.compile(r'^\s*source\s+\[file\s+join\s+\$_'),
]


def should_strip(line: str) -> bool:
    return any(p.search(line) for p in STRIP_PATTERNS)


def read_and_clean(filepath: str) -> str:
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()
    cleaned = [line for line in lines if not should_strip(line)]
    return "".join(cleaned).strip()


def build():
    os.makedirs(DIST_DIR, exist_ok=True)
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    parts = []

    # Header
    parts.append(f"""\
# ============================================================================
# OrCAD Checker Tool - Single File Bundle
# Auto-generated by build_bundle.py on {now}
# ============================================================================
#
# Usage in OrCAD Capture TCL Console:
#
#   source "C:/path/to/orcad_checker_all.tcl"
#
# Or copy to OrCAD auto-load directory:
#   $CDS_ROOT/tools/capture/tclscripts/capAutoLoad/
#
# ============================================================================

package require Tk
package require http

# TLS support: only load if available
if {{[catch {{package require tls}}] == 0}} {{
    http::register https 443 [list ::tls::socket -autoservername true]
}}

# Server URL (override before sourcing if needed)
if {{![info exists ::server_url]}} {{
    set ::server_url "http://localhost:8000"
}}

puts "Loading OrCAD Checker Tool (bundled)..."
""")

    # Bundle each file
    for relpath in BUNDLE_ORDER:
        filepath = os.path.join(SCRIPT_DIR, relpath.replace("/", os.sep))
        if not os.path.exists(filepath):
            print(f"WARNING: {filepath} not found, skipping")
            continue

        content = read_and_clean(filepath)

        # Strip duplicate package require lines (already in header)
        content = re.sub(r'^\s*package\s+require\s+(Tk|http|tls)\b.*$', '',
                         content, flags=re.MULTILINE)
        # Strip duplicate TLS registration block
        content = re.sub(
            r'set\s+_has_tls\s+\[catch.*?unset\s+_has_tls',
            '', content, flags=re.DOTALL)
        # Strip duplicate server_url default
        content = re.sub(
            r'if\s+\{!\[info\s+exists\s+::server_url\]\}.*?\}',
            '', content, flags=re.DOTALL)

        parts.append(f"""\
# ────────────────────────────────────────────────────────────────
# {relpath}
# ────────────────────────────────────────────────────────────────
{content}
""")

    # Inline extract_design.tcl (the proc only, no auto-run or source lines)
    extract_path = os.path.join(SCRIPT_DIR, "extract_design.tcl")
    if os.path.exists(extract_path):
        content = read_and_clean(extract_path)
        # Remove the auto-run block at the end
        content = re.sub(
            r'#\s*Auto-run if executed directly.*$', '', content, flags=re.DOTALL)
        parts.append(f"""\
# ────────────────────────────────────────────────────────────────
# extract_design.tcl
# ────────────────────────────────────────────────────────────────
{content}
""")

    # Entry point (from orcad_checker.tcl, just the tail)
    parts.append("""\
# ============================================================================
# Entry Point
# ============================================================================

puts "OrCAD Checker Tool loaded."
puts "  - 7 checkers available"
puts "  - Server: $::server_url"
puts ""
puts "Commands:"
puts "  orcad_checker_gui      - Open GUI"
puts "  run_all_checks         - Run all checks (console)"
puts "  extract_and_export     - Export design to JSON"
puts ""

# Auto-open GUI
orcad_checker_gui
""")

    output_path = os.path.join(DIST_DIR, "orcad_checker_all.tcl")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))

    size_kb = os.path.getsize(output_path) / 1024
    print(f"Built: {output_path} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    build()
