# Load all checker scripts
set _checker_dir [file dirname [info script]]

source [file join $_checker_dir duplicate_refdes.tcl]
source [file join $_checker_dir missing_attributes.tcl]
source [file join $_checker_dir unconnected_pins.tcl]
source [file join $_checker_dir footprint_validation.tcl]
source [file join $_checker_dir power_net_naming.tcl]
source [file join $_checker_dir net_naming.tcl]
source [file join $_checker_dir single_pin_nets.tcl]
source [file join $_checker_dir check_decoupling_caps.tcl]
source [file join $_checker_dir check_unused_pin_handling.tcl]
source [file join $_checker_dir check_esd_protection.tcl]
source [file join $_checker_dir check_i2c_pullups.tcl]
source [file join $_checker_dir check_crystal_load_caps.tcl]
source [file join $_checker_dir check_reset_pin.tcl]
source [file join $_checker_dir check_test_points.tcl]
source [file join $_checker_dir check_power_voltage_label.tcl]
source [file join $_checker_dir check_impedance_matching.tcl]
source [file join $_checker_dir check_standard_values.tcl]
source [file join $_checker_dir check_thermal_pad.tcl]
source [file join $_checker_dir check_connector_pinout.tcl]
